spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: 1111
    driver-class-name: org.postgresql.Driver
mybatis:
  type-aliases-package: com.project.trip_road
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel: true